name: gif
description: Control a gif using flutter animation controller. You can either specify a fixed duration or set the framerate of the playback.
version: 2.1.1
homepage: https://github.com/pierluigizagaria/flutter_gif

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:

